/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: ['class', 'data-mode="dark"'],
  theme: {
    extend: {
      colors: {
        'primary-light': 'var(--color-primary-light)',
        'primary-lighter': 'var(--color-primary-lighter)',
        primary: 'var(--color-primary)',
        'primary-darker': 'var(--color-primary-darker)',
        'primary-deepest': 'var(--color-primary-deepest)',
        'secondary-light': 'var(--color-secondary-light)',
        'secondary-lighter': 'var(--color-secondary-lighter)',
        secondary: 'var(--color-secondary)',
        'secondary-darker': 'var(--color-secondary-darker)',
        'secondary-deepest': 'var(--color-secondary-deepest)',
        'negative-light': 'var(--color-negative-light)',
        'negative-lighter': 'var(--color-negative-lighter)',
        negative: 'var(--color-negative)',
        'negative-darker': 'var(--color-negative-darker)',
        'negative-deepest': 'var(--color-negative-deepest)',
        'success-light': 'var(--color-success-light)',
        'success-lighter': 'var(--color-success-lighter)',
        success: 'var(--color-success)',
        'success-darker': 'var(--color-success-darker)',
        'success-deepest': 'var(--color-success-deepest)',
        'warning-light': 'var(--color-warning-light)',
        'warning-lighter': 'var(--color-warning-lighter)',
        warning: 'var(--color-warning)',
        'warning-darker': 'var(--color-warning-darker)',
        'warning-deepest': 'var(--color-warning-deepest)',
        'info-light': 'var(--color-info-light)',
        'info-lighter': 'var(--color-info-lighter)',
        info: 'var(--color-info)',
        'info-darker': 'var(--color-info-darker)',
        'info-deepest': 'var(--color-info-deepest)',
        'action-primary-active': 'var(--color-action-primary-active)',
        'action-primary-hover': 'var(--color-action-primary-hover)',
        'action-primary-selected': 'var(--color-action-primary-selected)',
        'action-primary-focus': 'var(--color-action-primary-focus)',
        'action-secondary-active': 'var(--color-action-secondary-active)',
        'action-secondary-hover': 'var(--color-action-secondary-hover)',
        'action-secondary-selected': 'var(--color-action-secondary-selected)',
        'action-secondary-focus': 'var(--color-action-secondary-focus)',
        'action-disabled': 'var(--color-action-disabled)',
        'action-disabled-background': 'var(--color-action-disabled-background)',
        'common-white': '--color-common-white',
        'common-black': 'var(--color-common-black)',
        'neutral-grey-50': '--color-neutral-grey-50',
        'neutral-grey-100': 'var(--color-neutral-grey-100)',
        'neutral-grey-200': '--color-neutral-grey-200',
        'neutral-grey-300': 'var(--color-neutral-grey-300)',
        'neutral-grey-400': '--color-neutral-grey-400',
        'neutral-grey-500': 'var(--color-neutral-grey-500)',
        'neutral-grey-600': '--color-neutral-grey-600',
        'neutral-grey-700': 'var(--color-neutral-grey-700)',
        'neutral-grey-800': 'var(--color-neutral-grey-800)',
        'neutral-grey-900': 'var(--color-neutral-grey-900)',
      },
    },
    backgroundColor: ({ theme }) => ({
      'background-default': 'var(--color-background-default)',
      'background-surface': 'var(--color-background-surface)',
      'background-overlay': 'var(--color-background-overlay)',
      ...theme('borderColor'),
    }),
    textColor: ({ theme }) => ({
      'primary-text': 'var(--color-text-primary)',
      'secondary-text': 'var(--color-text-secondary)',
      'disabled-text': 'var(--color-text-disabled)',
      ...theme('colors'),
    }),
    divideColor: ({ theme }) => ({
      'divider-black': 'var(--color-divider-black)',
      'divider-white': 'var(--color-divider-white)',
      ...theme('borderColor'),
    }),
    placeholderColor: ({ theme }) => theme('colors'),
    borderColor: ({ theme }) => theme('colors'),
    caretColor: ({ theme }) => theme('colors'),
  },
  plugins: [],
};
